### ISSUE TITLE
Adding stroke and gradient to font from layout file

### ISSUE THREAD

**Issue by okhan80** [andymeneely/squib#106]
Is there a way to use a yaml layout file to add stroke color and size, as well as color gradient to font being rendered on the cards?

**Comment by andymeneely** [comment]
Yes! As of v0.6, `stroke_width:` and `stroke_color:` are supported for `text`. The `stroke_color` supports gradients. And they can be put into your layout file as usual.

http://andymeneely.github.io/squib/doc/Squib/Deck.html#text-instance_method

These samples demonstrate it: 
https://github.com/andymeneely/squib/blob/master/samples/text_options.rb
https://github.com/andymeneely/squib/blob/master/samples/gradients.rb

Also, as part of the upcoming release (v0.7), I've added some more customization (stroke-and-fill vs. fill-and-stroke).

**Comment by okhan80** [comment]
Thanks for getting back to me so quickly! However, I am still encountering issues with stroke using your latest build.

In my layout file I have setup the Defend text as follows:
Defend:
  extends: bonus1 # from hand.yml
  font: Aleo bold 70
  color: '#f8fbfd'
  stroke_color: '#2b1f1f'
  stroke_width: 2.0
  y: += 70

However, I do not see that stroke color being drawn around that text. Any further insight would be most appreciated! Thanks again!

**Comment by okhan80** [comment]
Some additional info. If I force the stroke to draw inside of the script itself, the stroke is never aligned with the actual numbers themselves. It seems that they are being drawn at a higher scale and offset to the top right of the actual text. You can see this same effect through some of the examples you have linked to as well, when they are being generated on a new card.

**Comment by andymeneely** [comment]
Yes - these are bugs that should be fixed in the next release (coming soon TM). If you're comfortable testing a pre-release, you can test out this behavior on my master branch. Just set your Gemfile to master and do `bundle install` http://andymeneely.github.io/squib/doc/file.README.html#Testing_Pre-Builds

Sorry about that.

**Comment by okhan80** [comment]
No problem! I am just glad I can help you resolve some of the bugs as I enjoy using your program.

I have changed the Gemfile to the master branch and completed a `bundle install` on the file. I am still encountering some of the rendering issues on the cards. I have attached an image of the issue along with the code that I am using in the ruby file to try to render the strokes. 

`text str: deck[key], layout: key, stroke_color: :black, stroke_width: 4`

![exampleimage](https://cloud.githubusercontent.com/assets/444527/9068206/9de7fb38-3aa7-11e5-855c-da4e4a58bbeb.png)

**Comment by andymeneely** [comment]
Which part of the image should I be looking at? It's hard to tell from the one line since I don't know what `key` is set to. 

In any case - I'll do some more testing on this. I'll be off for a few days after today, so it might be a little while. 

BTW - that's some great artwork! Really well done.

**Comment by andymeneely** [comment]
I know it's been a while, but I hope this bug hasn't blocked you. I can't seem to reproduce this. Can you could give a minimal example?

**Comment by andymeneely** [comment]
Now that's it's been 13 months since my last comment, I'm closing this.
